### ISSUE TITLE
Include Popper (Floating UI) styles in the "layout only" stylesheets or let include it manually

### ISSUE THREAD

**Issue by ilyakonrad** [GetStream/stream-chat-angular#571] opened 2024-03-27 13:52 UTC
I'm trying to build styles from scratch, so I'm using `stream-chat-angular/src/assets/styles/v2/scss/index.layout.scss` as my starting point. However that seems to break Popper styles. This is what I see when hovering the checkmark icon:

![image](https://github.com/GetStream/stream-chat-angular/assets/25200186/539b9b5c-000b-4653-803a-25f5c73ebfed)

**Comment by szuperaz** [comment] 2024-03-28 12:10
I've tested this with the [sample app](https://github.com/GetStream/stream-chat-angular?tab=readme-ov-file#sample-app) and the popper styles worked for me if I import `stream-chat-angular/src/assets/styles/v2/scss/index.layout.scss`. I've tested both the message menu (...) and the checkmark icon. Please try to reproduce with the sample app, and I can take a deeper look.

**Comment by ilyakonrad** [comment] 2024-03-28 17:07
@szuperaz  Are you using the latest ngx-popperjs version?

**Comment by ilyakonrad** [comment] 2024-03-29 11:34
@szuperaz Here's the reproduction [stream-chat-ngx-popperjs-issue.zip](https://github.com/GetStream/stream-chat-angular/files/14803528/stream-chat-ngx-popperjs-issue.zip).

I see that they've changed some code 5 months ago while switching the core library from popperjs to floating ui.
Here's [one of the lines](https://github.com/tonysamperi/ngx-popperjs/commit/54780572a6955cd05967881dd872a107cfcec2c4#diff-8f4e1cdce33f0b214da0cede8597f1060d9f47d632f162540ff8832c23709021R31) which introduces some changes reflected in my screenshot.

**Comment by szuperaz** [comment] 2024-04-02 12:57
Thanks for the reproduction, I was able to see the issue. It's present even if you import the full SCSS. However the issue is gone if you use a version >=4.60.0. I'm going to close this issue, but feel free to reopen it if that doesn't solve it for you.

**Closed by szuperaz** 2024-04-02 12:57 UTC
